controllers/RbacmanagerController.php
<?php
namespace rusbitles\adminbase\controllers;

use rusbitles\adminbase\controllers\base\AdminController;
use rusbitles\adminbase\controllers\base\CommonAdminController;
use rusbitles\adminbase\models\forms\RbacGroup;
use rusbitles\adminbase\models\forms\RbacRights;
use rusbitles\adminbase\models\User;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

class RbacmanagerController extends CommonAdminController
{
    public static $modelTitles = ['Группа', 'Группы', 'Групп'];

    public function getModelTitles() {
        return static::$modelTitles;
    }

    public function actionIndex() {
        $auth = Yii::$app->authManager;

        $resPermissions = [];
        $permissions = $auth->getRoles();
        foreach($permissions as $permission) {
            if((isset($permission->data['type']) && $permission->data['type'] != 'system' || !isset($permission->data['type']))) {
                $resPermissions[] = $permission;
            }
        }

        return $this->render('index', ['permissions' => $resPermissions]);
    }

    public function actionCreate($name = false) {
        if ($name === false) {
            $model = new RbacGroup();
        } else {
            $model = RbacGroup::getModel($name);
        }

        if (!$model) throw new NotFoundHttpException();

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if (isset($_POST['cancel'])) return [];

            $model->load(Yii::$app->request->post());
            return ActiveForm::validate($model);
        }

        if (isset($_POST['cancel'])) {
            $this->redirect(Yii::$app->urlManager->createUrl([$this->admin->id . '/rbacmanager/index']));

            \Yii::$app->end();
        }

        if (isset($_POST['save']) || isset($_POST['apply'])) {
            $model->roles = [];
            $model->permissions = [];
            $model->load(\Yii::$app->request->post());

            if ($model->save()) {
                if (isset($_POST['save'])) {
                    return $this->redirect(Yii::$app->urlManager->createUrl([$this->admin->id . '/rbacmanager/index']));
                } else {
                    return $this->redirect(Yii::$app->urlManager->createUrl([$this->admin->id . '/rbacmanager/create', 'name' => $model->name]));
                }
            }
        }

        return $this->render('@rusbitles/adminbase/views/base/create', ['models' => [$model], 'views' => ["@rusbitles/adminbase/views/rbacmanager/_form"]]);
    }
    
    public function actionRights($uid) {
        $user = User::findOne($uid);
        if (!$user) throw new NotFoundHttpException();
        
        $model = RbacRights::getModel($uid);

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if (isset($_POST['cancel'])) return [];

            $model->load(Yii::$app->request->post());
            return ActiveForm::validate($model);
        }

        if (isset($_POST['cancel'])) {
            $this->redirect(Yii::$app->urlManager->createUrl([$this->admin->id . '/usermanager/update', 'id' => $uid]));

            \Yii::$app->end();
        }

        if (isset($_POST['save']) || isset($_POST['apply'])) {
            $model->roles = [];
            $model->permissions = [];
            $model->load(\Yii::$app->request->post());

            if ($model->save($uid)) {
                if (isset($_POST['save'])) {
                    return $this->redirect(Yii::$app->urlManager->createUrl([$this->admin->id . '/usermanager/update', 'id' => $uid]));
                } else {
                    return $this->redirect(Yii::$app->urlManager->createUrl([$this->admin->id . '/rbacmanager/rights', 'uid' => $uid]));
                }
            }
        }

        return $this->render('@rusbitles/adminbase/views/base/create', ['models' => [$model], 'views' => ["@rusbitles/adminbase/views/rbacmanager/_formrights"]]);
    }

    public function actionDelete($name) {
        RbacGroup::deleteModel($name);
        
        return $this->redirect(Yii::$app->urlManager->createUrl([$this->admin->id . '/rbacmanager/index']));
    }
}

views/rbacmanager/_form.php
<?=$form->field($model, "name")?>
<?=$form->field($model, "description")?>

<?php $permissions = \rusbitles\adminbase\models\forms\RbacGroup::getPermissions()?>
<?php $roles = \rusbitles\adminbase\models\forms\RbacGroup::getRoles()?>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                <input class="all_check" id="all1" data-aim=".col1" type="checkbox" />
                <label class="control-label" for="all1">Выделить все</label>
            </th>
            <th>
                <input class="all_check" id="all2" data-aim=".col2" type="checkbox" />
                <label class="control-label" for="all2">Выделить все</label>
            </th>
            <th>
                <input class="all_check" id="all3" data-aim=".col3" type="checkbox" />
                <label class="control-label" for="all3">Выделить все</label>
            </th>
        </tr>
    </thead>
    <tbody>
        <? foreach($permissions['table'] as $permissionName => $permissionRow) { ?>
            <tr>
                <? $i = 0; foreach($permissionRow as $operationName => $permission) { $i++; ?>
                    <td>
                        <input class="col<?=$i?>" type="checkbox" name="<?=$model->formName()?>[permissions][]" id="permission-<?=$permission->name?>" value="<?=$permission->name?>"<?=(in_array($permission->name, $model->permissions)?' checked':'')?>/>
                        <label class="control-label" for="permission-<?=$permission->name?>"><?=$permission->description?></label>
                    </td>
                <? } ?>
            </tr>
        <? } ?>
        <tr><td>Другие права</td></tr>
        <? foreach($permissions['common'] as $k => $permission) { ?>
            <tr>
                <td>
                    <input type="checkbox" name="<?=$model->formName()?>[permissions][]" id="permission-<?=$permission->name?>" value="<?=$permission->name?>"<?=(in_array($permission->name, $model->permissions)?' checked':'')?>/>
                    <label class="control-label" for="permission-<?=$permission->name?>"><?=$permission->description?></label>
                </td>
            </tr>
        <? } ?>
            <tr><td>Другие группы</td></tr>
        <? foreach($roles as $k => $role) { if ($role->name != $model->name) { ?>
            <tr>
                <td>
                    <input type="checkbox" name="<?=$model->formName()?>[roles][]" id="role-<?=$role->name?>" value="<?=$role->name?>"<?=(in_array($role->name, $model->roles)?' checked':'')?>/>
                    <label class="control-label" for="role-<?=$role->name?>"><?=$role->description?></label>
                </td>
            </tr>
        <? } } ?>
    </tbody>
</table>

views/rbacmanager/_formrights.php
<?php $permissions = \rusbitles\adminbase\models\forms\RbacGroup::getPermissions()?>
<?php $roles = \rusbitles\adminbase\models\forms\RbacGroup::getRoles()?>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                <input class="all_check" id="all1" data-aim=".col1" type="checkbox" />
                <label class="control-label" for="all1">Выделить все</label>
            </th>
            <th>
                <input class="all_check" id="all2" data-aim=".col2" type="checkbox" />
                <label class="control-label" for="all2">Выделить все</label>
            </th>
            <th>
                <input class="all_check" id="all3" data-aim=".col3" type="checkbox" />
                <label class="control-label" for="all3">Выделить все</label>
            </th>
        </tr>
    </thead>
    <tbody>
        <? foreach($permissions['table'] as $permissionName => $permissionRow) { ?>
            <tr>
                <? $i = 0; foreach($permissionRow as $operationName => $permission) { $i++; ?>
                    <td>
                        <input class="col<?=$i?>" type="checkbox" name="<?=$model->formName()?>[permissions][]" id="permission-<?=$permission->name?>" value="<?=$permission->name?>"<?=(in_array($permission->name, $model->permissions)?' checked':'')?>/>
                        <label class="control-label" for="permission-<?=$permission->name?>"><?=$permission->description?> (<?=$permission->name?>)</label>
                    </td>
                <? } ?>
            </tr>
        <? } ?>
        <tr><td>Другие права</td></tr>
        <? foreach($permissions['common'] as $k => $permission) { ?>
            <tr>
                <td>
                    <input type="checkbox" name="<?=$model->formName()?>[permissions][]" id="permission-<?=$permission->name?>" value="<?=$permission->name?>"<?=(in_array($permission->name, $model->permissions)?' checked':'')?>/>
                    <label class="control-label" for="permission-<?=$permission->name?>"><?=$permission->description?></label>
                </td>
            </tr>
        <? } ?>
            <tr><td>Другие группы</td></tr>
        <? foreach($roles as $k => $role) { ?>
            <tr>
                <td>
                    <input type="checkbox" name="<?=$model->formName()?>[roles][]" id="role-<?=$role->name?>" value="<?=$role->name?>"<?=(in_array($role->name, $model->roles)?' checked':'')?>/>
                    <label class="control-label" for="role-<?=$role->name?>"><?=$role->description?></label>
                </td>
            </tr>
        <? } ?>
    </tbody>
</table>

views/rbacmanager/index.php
<h1>Группы пользователей</h1>

<div class="btn-group actionButtons">
    <a class="btn btn-default" href="<?=Yii::$app->urlManager->createUrl([$this->context->admin->id . '/rbacmanager/create'])?>"><i class="fa fa-plus"></i> Добавить</a>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Код</th>
            <th>Описание</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <? foreach($permissions as $permission) { ?>
            <tr>
                <td><?=$permission->name?></td>
                <td><?=$permission->description?></td>
                <td>
                    <a href="<?=Yii::$app->urlManager->createUrl([$this->context->admin->id . '/rbacmanager/create', 'name' => $permission->name])?>"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a href="<?=Yii::$app->urlManager->createUrl([$this->context->admin->id . '/rbacmanager/delete', 'name' => $permission->name])?>" data-confirm="Вы точно хотите удалить запись?"><span class="glyphicon glyphicon-trash"></span></a>
                </td>
            </tr>
        <? } ?>
    </tbody>
</table>