models/User.php
<?php

namespace rusbitles\adminbase\models;

use Yii;
use yii\web\IdentityInterface;

class User extends CActiveRecord implements IdentityInterface
{
    public $rememberMe = 0;
    public $newPassword = '';
    public $fullname_search;

    public function rules()
    {
        return [
            [['username', 'email', 'name', 'last_name', 'second_name'], 'string', 'max' => 255, 'on' => ['login', 'register', 'default']],
            [['newPassword'], 'string', 'min' => 6, 'max' => 16, 'on' => ['login', 'register', 'default'], 'tooLong' => 'Значение «{attribute}» должно содержать максимум 16 символов.', 'tooShort' => 'Значение «{attribute}» должно содержать минимум 6 символов.'],
            [['password'], 'string', 'on' => ['login', 'register']],
            [['public', 'rememberMe'], 'integer', 'on' => ['login', 'register', 'default']],
            [['email'], 'email', 'on' => ['login', 'register', 'default']],
            [['email', 'username'], 'unique', 'on' => ['register', 'default']],

            [['username'], 'required', 'on' => ['login', 'register']],
            [['password'], 'required', 'on' => 'login'],
            [['email'], 'required', 'on' => 'register'],
            [['password'], 'validatePassword', 'on' => 'login'],

            [['fullname_search'], 'string'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Логин',
            'password' => 'Пароль',
            'email' => 'Адрес электронной почты',
            'public' => 'Публикация',
            'rememberMe' => 'Запомнить',
            'name' => 'Имя',
            'fullName' => 'Фио',
            'fullname_search' => 'Фио',
            'image' => 'Аватар',
            'last_name' => 'Фамилия',
            'second_name' => 'Отчество',
            'newPassword' => 'Пароль',
        ];
    }

    public function register($backController) {
        $this->scenario = 'register';
        if ($this->save()) {
            $this->auth_key = substr(md5(time()), 10, 18);
            $this->public = 0;
            $this->save(false, ['auth_key', 'public']);
            
            $this->send_register_mail($backController);
            
            return true;
        }
        
        return false;
    }
    
    public function send_register_mail($backController) {
        Yii::$app->mailer->setViewPath('@rusbitles/adminbase/mail');
        Yii::$app->mailer->compose('register', ['backController' => $backController, 'user' => $this])
            ->setFrom(Settings::getParam('site', 'adminEmail'))
            ->setTo($this->email)
            ->setSubject('Завершение регистрации на сайте «' . Yii::$app->params['name'] . '»')
            ->send();
    }
    
    public static function confirmRegistration($uid, $auth_code) {
        $user = User::find()->where(['id' => $uid])->andWhere(['auth_key' => $auth_code])->one();
        if ($user && $auth_code != '') {
            $user->auth_key = '';
            $user->public = 1;
            $user->save(false, ['auth_key', 'public']);
            
            return $user;
        }
        
        return false;
    }

    public function login()
    {
        $this->scenario = 'login';
        if ($this->validate()) {

            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        
        return false;
    }

    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();
            
            if (!$user || $user->password != $this->generatePassword($this->password) || $user->public == 0) {
                $this->addError($attribute, 'Неверно введен логин или пароль');
            }
        }
    }

    public $_user = false;
    public function getUser()
    {
        if ($this->_user === false) {
            $user = static::findOne(['username' => $this->username]);
            if ($user) $this->_user = $user;
        }

        return $this->_user;
    }
    
    public function getFullName() {
        $fn = [];
        if ($this->last_name != '') $fn[] = $this->last_name;
        if ($this->name != '') $fn[] = $this->name;
        if ($this->second_name != '') $fn[] = $this->second_name;
        if (count($fn) > 0) {
            return implode(' ', $fn);
        } else {
            return $this->username;
        }
    }

    public function beforeSave($insert)
    {
        if($this->newPassword !== false && $this->newPassword != '') {
            $this->password = $this->generatePassword($this->newPassword);
        }

        return parent::beforeSave($insert);
    }

    public static function tableName()
    {
        return 'system_users';
    }
    
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    public function generatePassword($password) {
        return md5($password);
    }
    
    public function formName()
    {
        return 'User'.$this->scenario;
    }

    public function getSocs() {
        return $this->hasMany(UserSoc::className(), ['user_id' => 'id']);
    }
}

controllers/UserController.php
<?php
namespace rusbitles\adminbase\controllers;

use rmrevin\yii\ulogin\AuthAction;
use rusbitles\adminbase\controllers\base\CommonAdminController;
use rusbitles\adminbase\helpers\SystemTools;
use rusbitles\adminbase\models\User;
use rusbitles\adminbase\models\UserSoc;
use Yii;
use yii\web\NotFoundHttpException;

class UserController extends CommonAdminController
{
    public $doHistory = false;
    public $layout = 'gentelella_form';
    public $requireAuth = false;

    public function actionLogin()
    {
        $this->title = "Вход на сайт";
        $this->h1title = "Вход на сайт";


        if (!\Yii::$app->user->isGuest) {
            return $this->redirect($this->lastPage);
        }
        
        $model = new User();
        $model->scenario = 'login';
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect($this->lastPage);
        }
        return $this->render('@rusbitles/adminbase/views/user/login', ['model' => $model]);
    }

    public function actionLogout($back = '/')
    {
        Yii::$app->user->logout();

        return $this->redirect($back);
    }

    public function actionRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect('/');
        }

        $success = false;
        $model = new RegisterForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $success = true;

            $newUser = new User();
            $newUser->username = $model->username;
            $newUser->email = $model->email;
            $newUser->password = md5($model->password);
            if ($model->name == '') {
                $newUser->name = $model->username;
            } else {
                $newUser->name = $model->name;
            }
            $newUser->public = 0;
            $newUser->auth_key = substr(md5(time() . $newUser->username), 5, 6);
            $newUser->save();

            Yii::$app->mailer->compose('register', ['model' => $newUser])
                ->setFrom(Settings::getParam('adminEmail'))
                ->setTo($newUser->email)
                ->setSubject('Успешная регистрация на сайте «'.Yii::$app->params['name'].'»')
                ->send();
        }

        return $this->render('register', ['model' => $model, 'success' => $success]);
    }

    public function actionConfirm($id = false, $code = '')
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect('/');
        }

        $success = false;
        if ($id !== false) {
            $model = User::findOne(intval($id));
            if ($model->auth_key != '' && $model->auth_key == $code) {
                $model->auth_key = '';
                $model->public = 1;
                $model->save();

                Yii::$app->user->login($model, 3600*24*30);

                $success = true;
            }
        } else {
            throw new NotFoundHttpException();
        }

        return $this->render('confirm', ['model' => $model, 'success' => $success]);
    }

    public function actionRecovery()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect('/');
        }

        $success = false;
        $model = new RecoveryForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $userLogin = User::find()->andWhere(['=', 'username', $model->username])->andWhere(['=', 'public', 1])->one();
            $userEmail = User::find()->andWhere(['=', 'email', $model->email])->andWhere(['=', 'public', 1])->one();
            $user = $userLogin;
            if (!$user) $user = $userEmail;

            if ($user) {
                $time = intval(end(explode(':', $user->recovery)));

                if ($time + 1800 < time()) {
                    $user->recovery = substr(md5(time() . $user->password), 4, 6) . ':' . time();
                    $user->save();

                    Yii::$app->mailer->compose('recovery', ['model' => $user])
                        ->setFrom(Settings::getParam('adminEmail'))
                        ->setTo($user->email)
                        ->setSubject('Восстановление пароля на сайте «' . Yii::$app->params['name'] . '»')
                        ->send();

                    $success = true;
                } else {
                    $model->addError('username', 'Письмо для восстановления пароля уже было отправлено! Повторное отправление возможно через 30 минут.');
                }
            } else {
                $model->addError('username', 'Пользователь не найден!');
            }
        }

        return $this->render('recovery', ['model' => $model, 'success' => $success]);
    }

    public function actionChangepass($id = false, $code = '')
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect('/');
        }

        $success = false;
        if ($id !== false) {
            $user = User::findOne(intval($id));
            if (!$user || $user->recovery == '') throw new NotFoundHttpException();
            $recovery = explode(':', $user->recovery);
            if ($recovery[0] != $code || intval($recovery[1]) + 1800 < time()) throw new NotFoundHttpException();

            $model = new ChangepassForm();
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $user->password = md5($model->password);
                $user->recovery = '';
                $user->save();

                $success = true;
            }
        } else {
            throw new NotFoundHttpException();
        }

        return $this->render('changepass', ['model' => $model, 'success' => $success]);
    }

    public function actionUlogin($backurl = false) {
        $uAuth = new AuthAction('ulogin', $this);
        $uAuth->successCallback = 'rusbitles\adminbase\controllers\UserController::uloginSuccessCallback';
        $uAuth->run();

        if ($backurl !== false) {
            return $this->redirect($backurl);
        } else {
            return $this->redirect($this->lastPage);
        }
    }

    public static function uloginSuccessCallback($attributes)
    {
        if (!empty($attributes)) {
            $soc = UserSoc::find()->where(['network' => $attributes['network'], 'uid' => $attributes['uid']])->one();
            if (!$soc) {
                $soc = new UserSoc();
                $soc->network = $attributes['network'];
                $soc->uid = $attributes['uid'];
                $soc->soc_array = json_encode($attributes);
            }

            if (Yii::$app->user->isGuest) {
                if ($soc->isNewRecord) {
                    $user = User::find()->where(['username' => $attributes['email']])->one();
                } else {
                    $user = $soc->user;
                }
                if (!$user) {
                    $user = new User();
                    $user->username = $attributes['email'];
                    $user->password = substr(md5(time()), 5, 10);
                    $user->email = $attributes['email'];
                    $user->public = 1;
                    $user->name = $attributes['first_name'];
                    $user->last_name = $attributes['last_name'];
                }

                if ($user->image == '') {
                    $user->image = SystemTools::getExternalFile($attributes['photo_big'], 'user');
                }

                if ($user->save()) {
                    $soc->user_id = $user->id;
                    $soc->save();

                    Yii::$app->user->login($user);
                }
            } else {
                $soc->user_id = Yii::$app->user->id;
                $soc->save();
            }
        }
    }
}

views/user/changepass.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<div class="page">
    <div class="page-container">
        <div class="page-content">
            <?php if (!$success) { ?>
                <?php $form = ActiveForm::begin([
                    'id' => 'changepass-form',
                    'options' => ['class' => 'form-horizontal'],
                    'fieldConfig' => [
                        'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                        'labelOptions' => ['class' => 'col-lg-1 control-label'],
                    ],
                ]); ?>
                <?php if($form->errorSummary($model)) { ?>
                    <div>
                        <?=$form->errorSummary($model)?>
                    </div>
                <?php } ?>
                <label class="label-text">
                    <span>Пароль<?=$model->isAttributeRequired('password')?' *':''?></span>
                    <?=Html::input('password', 'ChangepassForm[password]', $model->password)?>
                </label>
                <label class="label-text">
                    <span>Повторите пароль<?=$model->isAttributeRequired('confirmPassword')?' *':''?></span>
                    <?=Html::input('password', 'ChangepassForm[confirmPassword]', $model->confirmPassword)?>
                </label>
                <?=Html::submitButton('Смена пароля', ['class' => 'lk-save', 'name' => 'changepass-button']) ?>
                <?php ActiveForm::end(); ?>
            <?php } else { ?>
                <p>Пароль успешно изменен!</p>
            <?php } ?>
        </div>
    </div>
</div>

views/user/confirm.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<div class="page">
    <div class="page-container">
        <div class="page-content">
            <?php if (!$success) { ?>
                <p>Ошибка!</p>
            <?php } else { ?>
                <p>Вы успешно подтвердили регистрацию! Вы автоматически авторизованы на сайте!</p>
            <?php } ?>
        </div>
    </div>
</div>

views/user/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use rmrevin\yii\ulogin\ULogin;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php $form = ActiveForm::begin([
    "enableAjaxValidation" => false,
    "enableClientValidation" => false,
    "fieldConfig" => [
        "options" => [
            'class' => 'row',
        ],
        "template" => "<div class='col-sm-2 text-right'>{label}</div><div class='col-sm-8'>{input}\n{hint}\n{error}</div>",
    ],
    "fieldClass" => 'rusbitles\adminbase\classes\RBField',
]); ?>
    <?php if($form->errorSummary($model)) { ?>
        <div>
            <?=$form->errorSummary($model)?>
        </div>
    <?php } ?>
    <?=$form->field($model, "username")?>
    <?=$form->field($model, "password")->passwordInput()?>
    <?=$form->field($model, "rememberMe")->checkbox()?>

    <div class='col-sm-offset-2'>
        <p>Авторизация через социальные сети: </p>
        <p>
            <?=ULogin::widget([
                // widget look'n'feel
                'display' => ULogin::D_PANEL,

                // required fields
                'fields' => [ULogin::F_FIRST_NAME, ULogin::F_LAST_NAME, ULogin::F_EMAIL, ULogin::F_PHOTO_BIG],

                // optional fields
                'optional' => [ULogin::F_BDATE],

                // login providers
                'providers' => [ULogin::P_VKONTAKTE, ULogin::P_FACEBOOK, ULogin::P_TWITTER, ULogin::P_GOOGLE],

                // login providers that are shown when user clicks on additonal providers button
                'hidden' => [],

                // where to should ULogin redirect users after successful login
                'redirectUri' => Yii::$app->urlManager->createUrl([$this->context->admin->id . '/user/ulogin']),

                // optional params (can be ommited)
                // force widget language (autodetect by default)
                'language' => ULogin::L_RU,

                // providers sorting ('relevant' by default)
                'sortProviders' => ULogin::S_RELEVANT,

                // verify users' email (disabled by default)
                'verifyEmail' => '0',

                // mobile buttons style (enabled by default)
                'mobileButtons' => '1',
            ])?>
        </p>
    </div>

    <div class="col-sm-offset-2">
        <?=Html::submitButton('Войти', ['class' => 'btn']) ?>
        <p><a href="<?=Yii::$app->urlManager->createUrl(['base/user/recovery'])?>">Забыли пароль?</a></p>
    </div>
<?php ActiveForm::end(); ?>

views/user/recovery.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<div class="page">
    <div class="page-container">
        <div class="page-content">
            <?php if (!$success) { ?>
            <?php $form = ActiveForm::begin([
                'id' => 'recovery-form',
                'options' => ['class' => 'form-horizontal'],
                'fieldConfig' => [
                    'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                    'labelOptions' => ['class' => 'col-lg-1 control-label'],
                ],
            ]); ?>
                <?php if($form->errorSummary($model)) { ?>
                    <div>
                        <?=$form->errorSummary($model)?>
                    </div>
                <?php } ?>
                <label class="label-text">
                    <span>Имя пользователя<?=$model->isAttributeRequired('username')?' *':''?></span>
                    <?=Html::input('text', 'RecoveryForm[username]', $model->username)?>
                </label>
                <label class="label-text">
                    <span>Ваш Email<?=$model->isAttributeRequired('email')?' *':''?></span>
                    <?=Html::input('text', 'RecoveryForm[email]', $model->email)?>
                </label>
                <?=Html::submitButton('Восстановить', ['class' => 'lk-save', 'name' => 'recovery-button']) ?>
            <?php ActiveForm::end(); ?>
            <?php } else { ?>
               <p>Спасибо! На Вашу почту было отправлено письмо с дальнейшими указаниями.</p>
            <?php } ?>
        </div>
    </div>
</div>

views/user/register.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<div class="page">
    <div class="page-container">
        <div class="page-content">
            <?php if (!$success) { ?>
            <?php $form = ActiveForm::begin([
                'id' => 'register-form',
                'options' => ['class' => 'form-horizontal'],
                'fieldConfig' => [
                    'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                    'labelOptions' => ['class' => 'col-lg-1 control-label'],
                ],
            ]); ?>
                <?php if($form->errorSummary($model)) { ?>
                    <div>
                        <?=$form->errorSummary($model)?>
                    </div>
                <?php } ?>
                <label class="label-text">
                    <span>Имя пользователя<?=$model->isAttributeRequired('username')?' *':''?></span>
                    <?=Html::input('text', 'RegisterForm[username]', $model->username)?>
                </label>
                <label class="label-text">
                    <span>Ваш Email<?=$model->isAttributeRequired('email')?' *':''?></span>
                    <?=Html::input('text', 'RegisterForm[email]', $model->email)?>
                </label>
                <label class="label-text">
                    <span>Пароль<?=$model->isAttributeRequired('password')?' *':''?></span>
                    <?=Html::input('password', 'RegisterForm[password]', $model->password)?>
                </label>
                <label class="label-text">
                    <span>Повторите пароль<?=$model->isAttributeRequired('confirmPassword')?' *':''?></span>
                    <?=Html::input('password', 'RegisterForm[confirmPassword]', $model->confirmPassword)?>
                </label>
                <?php/*<label class="label-text">
                    <span>Ваше имя<?=$model->isAttributeRequired('name')?' *':''?></span>
                    <?=Html::input('text', 'RegisterForm[name]', $model->name)?>
                </label>*/?>
                <?=Html::submitButton('Регистрация', ['class' => 'lk-save', 'name' => 'register-button']) ?>
            <?php ActiveForm::end(); ?>
            <?php } else { ?>
               <p>Спасибо! Вы успешно зарегистрированы на сайте! На Вашу почту было отправлено письмо с ссылкой для активизации.</p>
            <?php } ?>
        </div>
    </div>
</div>