controllers/UsermanagerController.php
<?php
namespace rusbitles\adminbase\controllers;

use rusbitles\adminbase\controllers\base\AdminController;
use Yii;

class UsermanagerController extends AdminController
{
    public static $mainmenuHandle = 'usermanager';
    public static $modelName='User';
    public static $fullModelName='rusbitles\\adminbase\\models\\User';
    public $baseModel=true;
    public static $modelTitles = ['Пользователь', 'Пользователи', 'Пользователей'];
    public static $images = [
        'image' => '@webroot/up/user',
    ];
    public static $children = [
    ];
    public $parents = [
    ];
    public static $links = [
    ];

    public function init()
    {
        static::$fullModelName = Yii::$app->user->identityClass;
        parent::init();
    }

    public function searchFields()
    {
        return array_merge(parent::searchFields(), [
            'username' => ['type' => 'string'],
            'email' => ['type' => 'string'],
            'fullname_search' => ['type' => 'manual', 'function' => function($query, $model) {
                /** @var ActiveQuery $query */
                $parts = preg_split('/\s+/', $model->fullname_search);

                $rules = ['and'];
                foreach ($parts as $part) {
                    $rules[] = ['or', ['like', 'name', $part], ['like', 'second_name', $part], ['like', 'last_name', $part], ['like', 'email', $part]];
                }
                $query->andFilterWhere($rules);

                return $query;
            }],
        ]);
    }

    public function actionSpyauth($uid) {
        if (!Yii::$app->user->isGuest && Yii::$app->user->can('spyauthorize')) {
            $cn = Yii::$app->user->identityClass;
            $user = $cn::find()->where(['id' => $uid])->one();
            if ($user) {
                Yii::$app->user->login($user->getUser(), 0);
            }
        }
        return $this->redirect('/');
    }
}

views/usermanager/_form.php
<?php
use rusbitles\adminbase\helpers\AdminTools;

$cn = Yii::$app->user->identityClass;
?>

<?php if($model->isNewRecord) { ?>
    <?=$form->field($model, 'username')?>
<?php } ?>
<?=$form->field($model, 'newPassword')->passwordInput()?>
<?=$form->field($model, 'email')?>
<?=$form->field($model, 'name')?>
<?=$form->field($model, 'last_name')?>
<?=$form->field($model, 'second_name')?>
<?=AdminTools::generateImageInputs($model, $form, 'image')?>
<?=$form->field($model, 'public')->checkbox([], false)?>

views/usermanager/create.php
<?=$this->render('@rusbitles/adminbase/views/base/create', ['content' => $content])?>

views/usermanager/index.php
<?php
use rusbitles\adminbase\helpers\BImages;
use rusbitles\adminbase\models\User;
use yii\helpers\Html;

$fields = [
        'id',
        'username',
        [
            'attribute' => 'fullname_search',
            'value' => function ($model) {
                return $model->fullName;
            },
        ],
        'email',
        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Права доступа',
            'template' => '{rights}',
            'buttons' => [
                'rights' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-user"></span>', Yii::$app->urlManager->createUrl([$this->context->admin->id . '/rbacmanager/rights', 'uid' => $model->id]));
                },
            ],
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Войти под пользователем',
            'template' => '{spyauthorize}',
            'buttons' => [
                'spyauthorize' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-log-in"></span>', Yii::$app->urlManager->createUrl([$this->context->admin->id . '/usermanager/spyauth', 'uid' => $model->id]), ['data-confirm' => Yii::t('yii', 'Вы точно хотите авторизоваться под этим пользователем?')]);
                },
            ],
        ],
        'author',
        [
            'attribute' => 'soc_array',
            'label' => 'Социалки',
            'value' => function ($model) {
                return ($model->soc_array == '')?'Нет':'Да';
            },
        ],
        'public',
    ];
?>

<?=$this->render('@rusbitles/adminbase/views/base/index', ['fields' => $fields, 'dataProvider' => $dataProvider, 'item' => $item])?>

views/usermanager/update.php
<?=$this->render('@rusbitles/adminbase/views/base/update', ['model' => $model, 'tabs' => $tabs, 'content' => $content])?>